### ISSUE TITLE
matrix function 

### ISSUE THREAD

**Issue by Ellie7** [Ellie7/parrot-proj#10]
my current matrix function (yellowFunc) produces the same matrix each time when given a different table to work with, I can't work out why because its very similar to my crouse script which works fine, it's probably something silly that I can't see because I've stared at it for too long ... 
its the function that begins at line 51

**Comment by andbeck** [comment]
Couple of things...

a) `yellowFunc <- function(yellow){ stuff }` isn't best practice as _yellow_ is the data input.  Bit better to use

`yellowFunc <- function(dataSource){ stuff }` and then use `yellowFunc(yellow)`

also sensible to change `ysaFunc <- function (ysa) { stuff } ` to `ysaFunc <- function (dataSource) { stuff } ` and then be able to use `ysaFunc(ysa)`.

b) If you alter the above, you'll realise that the input to the yellowFunc is not yellow, but the output of `ysaFunc()`.

I think the workflow should be 

1. make a bunch of matrices using ysaFunc().
2. apply yellowFunc to each of (1)
3. apply eigen to each of (2)

```{r}
library(tidyverse) # to get purrr library

## Example idea ---------------------------------

matrix(rnorm(4), nrow = 2) # example 2 x 2 matrix of random numbers

# make 10 matrices of random numbers.
# this could be your yellowFunc
mat1<-map(1:10, .f = function(x) matrix(rnorm(4), nrow = 2))

# use these matrices in mat 1 and get the eigen system for each....
mat2<-map(mat1, function(x) eigen(x))

## Might work with yours... but needs your effort ---------------------------------

yellowMats <- map(1:10, function(x) yellowFunc(x)) #makes 10 matrices
outMats <- map(yellowMats, function(x) ysaFunc(x)) # makes 10 matrices
eigenOuts <- map(outMats, function(x) eigen(x))
```

Of course you can do this in a loop if you want instead of map().
