### ISSUE TITLE
Push and Pull Problem

### ISSUE THREAD

**Issue by Ellie7** [Ellie7/parrot-proj#5]
@andbeck @tdjames1 
It won't let push because I need to pull, but when I go to pull it won't let me because:
"error: You have not concluded your merge (MERGE_HEAD exists).
hint: Please, commit your changes before merging.
fatal: Exiting because of unfinished merge." 
but I don't know how to finish the merge? 
I think its a markdown doc that's causing the problem

**Comment by Ellie7** [comment]
Having a couple other issues with my script but won't create an issue for those until I can push them...

**Comment by tdjames1** [comment]
Oh dear, let's see if we can sort this out :) 

In the "Git" tab in RStudio, go to More > Shell... to open up a command prompt. In the prompt, enter

    git status

and paste the output here.

**Comment by Ellie7** [comment]
![image](https://user-images.githubusercontent.com/32646574/32340154-abe736aa-bff1-11e7-961a-904cc0dbcfea.png)
it won't let me copy and paste the output so I've screenshotted I hope you can read it okay :)

**Comment by Ellie7** [comment]
It's working now, I don't know why though!

**Comment by tdjames1** [comment]
That's odd - but good!

**Comment by Ellie7** [comment]
I'd spent ages trying to fix it as well, sorry to waste your time Tamora!

**Comment by tdjames1** [comment]
That's alright, I like a nice git problem :) 

I don't know exactly how RStudio uses git so it's hard to know what happened there - the output from your status request suggests that it had invoked a merge because there was a commit on the remote repository that differed from your local commits, but it hadn't quite completed it. Anyway, glad you sorted it out.
