### ISSUE TITLE
myFunc doesn't like 1s 

### ISSUE THREAD

**Issue by Ellie7** [Ellie7/parrot-proj#9]
@andbeck @tdjames1
I've finished all my coding for figure 1 now but it won't produce figure 1b correctly because my function (myFunc, well more my code within the function for calculating Ps and Gs) doesn't like it when the survivorship values are 1, the whole thing works fine with 0.999 so I think it's just the 1 thing.

**Comment by tdjames1** [comment]
Hi Ellie, you're right, there's a problem with setting survivorship to 1 because when you calculate the Ps and Gs you will be dividing by zero, which is not a good thing mathematically speaking. As you've discovered you can get around this by setting survivorship to 0.999 - that's a perfectly acceptable workaround.

**Comment by Ellie7** [comment]
Great. thank you Tamora :)
